---
title: "repo-prueba"
author: "Iratxe Valero Ochoa"
format:
  revealjs:
    embed-resources: true
editor: visual
execute:
  echo: true
---

## CARGA DE DATOS

datos de **accidentes de tráficos** en la ciudad de madrid en el 2020

```{r}

library(tidyverse)
datos <- read_csv(file= 'datos/accidentes.csv')
datos
```

------------------------------------------------------------------------

#### Resumen de los datos

```{r}

resumen <- datos |> count(sexo)
```

------------------------------------------------------------------------

### visualización

```{r}
#| code-fold: true
ggplot(resumen) + geom_col(aes(x=sexo, y=n,fill=sexo), alpha = 0.56) + ggthemes::scale_fill_colorblind() + theme_minimal()
```

------------------------------------------------------------------------

[visualización interactiva]{style="color:#bc68ed;"}

```{r}
#| code-fold: true
gg <- ggplot(resumen) + geom_col(aes(x=sexo, y=n,fill=sexo), alpha = 0.56) + ggthemes::scale_fill_colorblind() + theme_minimal()
plotly::ggplotly(gg)
```
